# General
title: Ajay Jain
description: "Hi there!"
avatar: ajay-column.jpg

# Social media
email: mailto:ajay@ajayjain.io
linkedin: https://www.linkedin.com/in/ajay-jain-3209a6113/
twitter: https://twitter.com/theajayjain
medium: https://medium.com/@theajayjain
github: https://github.com/theajayjain

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

kramdown:
  auto_ids: true

# Date/time
date: "%B %-d, %Y"
timezone: 

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "work"
    values:
      layout: "work"
  - scope:
      path: ""
      type: "category"
    values:
      layout: "category"
      
collections:
  pages:
    output: true
    permalink: :title
  posts:
    output: true
    permalink: /posts/:title
  work:
    output: true
    permalink: /work/:title
  categories:
    output: true
    permalink: categories/:title

# Exclude
exclude:
  - CNAME
  - readme.md
  - gemfiles/
  - Gemfile
#   - Gemfile.lock
#   - .sass-cache/
#   - .jekyll-cache/
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
